_wandb:
    value:
        cli_version: 0.21.0
        e:
            lyomp53abl6kuhbwqymlazpo4oivwvu7:
                codePath: train.sac.py
                codePathLocal: train.sac.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1023411220480"
                        used: "112050900992"
                email: krkcdeniz15@gmail.com
                executable: c:\Users\90546\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 276d86e6636e11d553cdf71b2a810cf40279107e
                    remote: https://github.com/Dkurkcu/reacher_customenv_v1.git
                host: DESKTOP-E3OIJ6K
                memory:
                    total: "14773178368"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\90546\Desktop\customenv\train.sac.py
                python: CPython 3.13.3
                root: C:\Users\90546\Desktop\customenv
                startedAt: "2025-07-07T13:03:58.739152Z"
                writerId: lyomp53abl6kuhbwqymlazpo4oivwvu7
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.13.3
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
algo:
    value: SAC
batch_size:
    value: 256
device:
    value: cpu
env:
    value: Custom Reacher v1
learning_rate:
    value: 0.0003
net_arch:
    value:
        - 256
        - 256
timesteps:
    value: 300000
