_wandb:
    value:
        cli_version: 0.21.0
        e:
            gcscqtm9l6cdfjrjvpguv50rcmrd1lyj:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1023411220480"
                        used: "107877699584"
                email: krkcdeniz15@gmail.com
                executable: c:\Users\90546\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 829d48d8d4607998e91a8a22cc10ac3efde1c2d9
                    remote: https://github.com/Dkurkcu/reacher_customenv_v1.git
                host: DESKTOP-E3OIJ6K
                memory:
                    total: "14773178368"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\90546\Desktop\customenv\train.py
                python: CPython 3.13.3
                root: C:\Users\90546\Desktop\customenv
                startedAt: "2025-07-07T09:33:36.279829Z"
                writerId: gcscqtm9l6cdfjrjvpguv50rcmrd1lyj
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.13.3
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
algo:
    value: PPO
env:
    value: Custom Reacher v1
learning_rate:
    value: 0.0001
reward_shaping:
    value: precision_bonus + progress + action_penalty + velocity_penalty
timesteps:
    value: 200000
